import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProvider";
import Logo from "@/components/Logo";
import ThemeSwitcher from "@/components/ThemeSwitcher"; // Ensure this import remains

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen min-w-full bg-background max-h-screen">
            <nav className="flex justify-between items-center border-b border-border h-[60px] px-4 py-2">
              <Logo />
              <div className="flex gap-4 items-center">
                {/* Add the key prop to ThemeSwitcher */}
                <ThemeSwitcher key="theme-switcher" />
              </div>
            </nav>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
